// <auto-generated />
namespace OnlineStore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OrderSupplierOrderClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OrderSupplierOrderClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201803151354259_Order-Supplier & Order-Client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
